allow-dbg-in-tests = true
allow-unwrap-in-tests = true

disallowed-methods = [
  # 禁用 unwrap,
  { path = "core::option::Option::unwrap", reason = "Use `expect` with a meaningful message, or handle the None case properly." },
  { path = "core::result::Result::unwrap", reason = "Use `expect` with a meaningful message, or handle the Err case properly." },
  # 禁用 to_ascii_lowercase, to_ascii_uppercase, to_lowercase, to_uppercase, replace, replacen
  { path = "str::to_ascii_lowercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_ascii_lowercase` instead." },
  { path = "str::to_ascii_uppercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_ascii_uppercase` instead." },
  { path = "str::to_lowercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_lowercase` instead." },
  { path = "str::to_uppercase", reason = "To avoid memory allocation, use `cow_utils::CowUtils::cow_to_uppercase` instead." },
  { path = "str::replace", reason = "To avoid memory allocation, use `cow_utils::CowUtils::replace` instead." },
  { path = "str::replacen", reason = "To avoid memory allocation, use `cow_utils::CowUtils::replacen` instead." },
]
